"""Sequence/Music Metrics Viewer.

Recomputes H_norm, mean motor cost, and hand-switch probability for every
already-saved song under data/music/ (real recordings) and data/sequence/
(generated sequences), auto-detected via app.song_library.list_song_entries()
- the same combined list music_playback.py/student_quiz.py use to pick a
song. The metrics themselves come from app.sequence_generator.evaluate_song(),
the exact same Action/compute_stats machinery the Experiment Sequence
Generator uses to accept/reject a candidate sequence while generating - so
a number shown here means exactly the same thing as the same-named column
there, whether the song was recorded by a teacher or generated by that
tool.

Two checkboxes (Show music / Show sequence) and a name filter box narrow
the table down; both apply instantly against data already loaded by the
last Refresh, rather than re-scanning disk on every keystroke or checkbox
click - see _apply_filters().

"Validate Stimulus Set" runs app.stimulus_validation over whichever
*generated* sequences are currently visible in the table (data/sequence/
only - a real recording's difficulty label isn't tied to the generator's
alpha/beta/gamma grammar, so grouping it into L1/L2/L3 wouldn't mean
anything), grouped into L1/L2/L3 by difficulty. That means the Show/
Filter controls above double as "which sequences to compare" - type a
batch name into "Name contains" to scope the comparison to one generation
run instead of pooling every generated sequence ever saved, then click
Validate; a confirmation dialog names the batch(es) about to be compared
before the report opens (see app/gui/stimulus_validation_dialog.py), so
picking the wrong filter is caught before running the analysis rather
than after.

Read-only otherwise: this doesn't generate or save anything, it only
reports what a saved fingering.json already contains. A real recording's
fingering can have unresolved/ambiguous notes (the camera pipeline
couldn't confidently match a finger) - those are excluded from the
metrics (see app.sequence_generator.sequence_from_fingering), so the
Resolved column shows how many of a song's notes actually went into the
numbers shown.
"""

import re
from dataclasses import dataclass
from typing import List, Optional

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from ..config import Config
from ..music_recording import MUSIC_DATA_DIR, META_FILENAME, SongMeta, song_dir
from ..sequence_generator import LEVEL_DIFFICULTY, SequenceStats, evaluate_song, format_sequence_for_display
from ..song_library import SongEntry, list_song_entries
from ..stimulus_validation import validate_stimulus_set
from .stimulus_validation_dialog import StimulusValidationDialog

COLUMNS = ["Entry", "Difficulty", "Resolved", "Fingers", "Notes", "H_norm", "Mean cost", "Hand-switch"]

METRICS_EXPLANATION = (
    "H_norm (0-1): how varied the sequence's transitions are (hand switches, finger jumps, key/note "
    "distance) - low means the same kind of move repeats a lot (predictable), high means transitions keep "
    "changing kind (less predictable).  "
    "Mean cost: average biomechanical effort per transition (finger-jump distance + key/note distance + a "
    "hand-switch penalty) - higher means the sequence is physically more demanding overall.  "
    "Hand-switch (0-1): fraction of transitions where the acting hand changes - 0 means one hand plays the "
    "whole sequence, higher means more back-and-forth between hands."
)

_DIFFICULTY_TO_LEVEL = {v: k for k, v in LEVEL_DIFFICULTY.items()}

# Matches the generator's default naming, "<batch>-<level symbol>-<id>" or
# just "<level symbol>-<id>" with no batch - so a batch name (if any) can be
# read back out of a saved sequence's own name for the confirmation dialog
# below. A hand-edited name that doesn't match this shape isn't an error,
# it just can't be attributed to a particular batch.
_SEQUENCE_NAME_PATTERN = re.compile(r"^(?:(?P<batch>.+)-)?(?P<symbol>[αβγ])-(?P<id>\d+)$")


def _parse_batch_name(name: str) -> str:
    match = _SEQUENCE_NAME_PATTERN.match(name)
    if not match:
        return "(unrecognized name format)"
    return match.group("batch") or "(no batch name)"


@dataclass
class _RowData:
    entry: SongEntry
    is_music: bool
    difficulty: Optional[int]
    stats: Optional[SequenceStats]  # None if evaluate_song() failed for this entry
    cells: List[str]  # COLUMNS[1:] - "Entry" itself is entry.label, shown separately


class SequenceMetricsWindow(QMainWindow):
    def __init__(self, cfg: Optional[Config] = None):
        super().__init__()
        self.setWindowTitle("Sequence/Music Metrics")
        self.cfg = cfg  # unused, accepted so the launcher can open this like every other tool
        self.resize(1500, 900)

        self._rows_data: List[_RowData] = []

        refresh_btn = QPushButton("Refresh")
        refresh_btn.clicked.connect(self._refresh)

        top_row = QHBoxLayout()
        top_row.addWidget(QLabel("Every song under data/music/ and data/sequence/, recomputed live:"))
        top_row.addStretch(1)
        top_row.addWidget(refresh_btn)

        self.show_music_check = QCheckBox("Show music")
        self.show_music_check.setChecked(True)
        self.show_music_check.toggled.connect(self._apply_filters)
        self.show_sequence_check = QCheckBox("Show sequence")
        self.show_sequence_check.setChecked(True)
        self.show_sequence_check.toggled.connect(self._apply_filters)

        self.search_edit = QLineEdit()
        self.search_edit.setPlaceholderText("Filter by name - blank shows everything")
        self.search_edit.textChanged.connect(self._apply_filters)

        filter_row = QHBoxLayout()
        filter_row.addWidget(self.show_music_check)
        filter_row.addWidget(self.show_sequence_check)
        filter_row.addWidget(QLabel("Name contains:"))
        filter_row.addWidget(self.search_edit, 1)

        self.table = QTableWidget(0, len(COLUMNS))
        self.table.setHorizontalHeaderLabels(COLUMNS)
        self.table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
        self.table.verticalHeader().setVisible(False)

        self.validate_btn = QPushButton("Validate Stimulus Set (L1 / L2 / L3, currently visible rows)")
        self.validate_btn.clicked.connect(self._validate_stimulus_set)

        metrics_label = QLabel(METRICS_EXPLANATION)
        metrics_label.setWordWrap(True)

        self.status_label = QLabel("")
        self.status_label.setWordWrap(True)

        central = QWidget()
        layout = QVBoxLayout(central)
        layout.addLayout(top_row)
        layout.addLayout(filter_row)
        layout.addWidget(self.table, 1)
        layout.addWidget(self.validate_btn)
        layout.addWidget(metrics_label)
        layout.addWidget(self.status_label)
        self.setCentralWidget(central)

        self._refresh()

    # ------------------------------------------------------------------
    # Loading (disk I/O - only on Refresh)
    # ------------------------------------------------------------------

    def _refresh(self) -> None:
        entries = list_song_entries()
        self._rows_data = []

        failed = []
        for entry in entries:
            is_music = entry.data_dir == MUSIC_DATA_DIR
            difficulty = self._read_difficulty(entry)

            try:
                actions, stats, total_notes = evaluate_song(entry.name, entry.data_dir)
            except Exception as exc:
                failed.append(f"{entry.label}: {exc}")
                self._rows_data.append(_RowData(entry, is_music, difficulty, None, ["-"] * (len(COLUMNS) - 1)))
                continue

            fingers, notes = format_sequence_for_display(actions)
            cells = [
                str(difficulty) if difficulty is not None else "?",
                f"{len(actions)}/{total_notes}",
                fingers,
                notes,
                f"{stats.h_norm:.3f}",
                f"{stats.mean_motor_cost:.3f}",
                f"{stats.hand_switch_prob:.3f}",
            ]
            self._rows_data.append(_RowData(entry, is_music, difficulty, stats, cells))

        if not entries:
            self.status_label.setText("No songs found under data/music/ or data/sequence/.")
        elif failed:
            self.status_label.setText(
                f"Loaded {len(entries) - len(failed)}/{len(entries)} - couldn't read: {'; '.join(failed)}"
            )
        else:
            self.status_label.setText(f"Loaded {len(entries)} song(s).")

        self._apply_filters()

    # ------------------------------------------------------------------
    # Filtering (in-memory only, no disk I/O - runs on every keystroke/toggle)
    # ------------------------------------------------------------------

    def _apply_filters(self) -> None:
        show_music = self.show_music_check.isChecked()
        show_sequence = self.show_sequence_check.isChecked()
        keyword = self.search_edit.text().strip().lower()

        self.table.setRowCount(0)
        for row_data in self._rows_data:
            if row_data.is_music and not show_music:
                continue
            if not row_data.is_music and not show_sequence:
                continue
            if keyword and keyword not in row_data.entry.label.lower():
                continue

            row = self.table.rowCount()
            self.table.insertRow(row)
            self._set_cell(row, 0, row_data.entry.label)
            for col, text in enumerate(row_data.cells, start=1):
                self._set_cell(row, col, text)

    def _set_cell(self, row: int, col: int, text: str) -> None:
        item = QTableWidgetItem(text)
        item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, item)

    @staticmethod
    def _read_difficulty(entry: SongEntry) -> Optional[int]:
        try:
            meta = SongMeta.load(song_dir(entry.name, entry.data_dir) / META_FILENAME)
        except Exception:
            return None
        return meta.difficulty

    # ------------------------------------------------------------------
    # Stimulus set validation - only the currently visible (filtered) rows
    # ------------------------------------------------------------------

    def _validate_stimulus_set(self) -> None:
        visible_labels = {self.table.item(row, 0).text() for row in range(self.table.rowCount())}

        records = []
        batches = set()
        for row_data in self._rows_data:
            if row_data.entry.label not in visible_labels:
                continue
            if row_data.is_music or row_data.stats is None or row_data.difficulty is None:
                continue
            level = _DIFFICULTY_TO_LEVEL.get(row_data.difficulty)
            if level is None:
                continue
            records.append((level, row_data.stats.mean_motor_cost, row_data.stats.h_norm))
            batches.add(_parse_batch_name(row_data.entry.name))

        if not records:
            QMessageBox.information(
                self,
                "Nothing to validate",
                "No generated sequences (data/sequence/) are currently visible. Adjust the Show/Filter controls "
                'above - e.g. type a batch name into "Name contains" - to pick which ones to compare, then try '
                "again.",
            )
            return

        batch_summary = ", ".join(sorted(batches))
        reply = QMessageBox.question(
            self,
            "Confirm sequences to compare",
            f"About to validate {len(records)} generated sequence(s) from batch(es): {batch_summary}.\n\n"
            "If this isn't the set you want to compare, click No and narrow the Show/Filter controls above "
            'first (e.g. type a batch name into "Name contains").',
        )
        if reply != QMessageBox.StandardButton.Yes:
            return

        report = validate_stimulus_set(records)
        dialog = StimulusValidationDialog(report, self)
        dialog.exec()
